(()=>{
const profileFields=[['full_name','','text'],['title','','text'],['eyebrow','','text'],['summary','','textarea'],['email','','email'],['phone','','text'],['location','','text'],['website_url','','url'],['linkedin_url','','url'],['github_url','','url'],['avatar_url','','url'],['availability','','text']];
const settingsFields=[['accent_color','','text'],['cv_url','','url'],['show_cv','','check'],['last_updated_text','','text'],['meta_description','','textarea']];
let previewRAF=0;
const clone=v=>{try{return structuredClone(v)}catch{return JSON.parse(JSON.stringify(v))}};
const val=(v,f='')=>v==null?f:String(v);
const arr=v=>Array.isArray(v)?v:[];
function readContainer(selector,fields,base={}){const box=document.querySelector(selector),out={...base};if(!box)return out;fields.forEach(([k,,t])=>{const el=box.querySelector(`[name="${CSS.escape(k)}"]`);if(!el)return;if(t==='check')out[k]=!!el.checked;else if(t==='number')out[k]=Number(el.value||0);else if(t==='lines')out[k]=String(el.value||'').split('\n').map(s=>s.trim()).filter(Boolean);else out[k]=String(el.value||'').trim()});return out}
function draftSnapshot(){const snap=clone(state);snap.profile=readContainer('#profile-form',profileFields,snap.profile||{});snap.settings=readContainer('#settings-form',settingsFields,snap.settings||{});if(!editCtx||!document.querySelector('#modal.open'))return snap;const form=document.querySelector('#modal-form');if(!form)return snap;
 if(editCtx.kind==='sectionMeta'){const fd=new FormData(form),name=String(fd.get('name')||'').trim()||'Untitled section',subtitle=String(fd.get('subtitle')||'').trim()||'Selected entries';if(editCtx.mode==='rename'){snap.sections=snap.sections.map(s=>String(s.id)===String(editCtx.id)?{...s,name,nav_label:name,subtitle}:s)}else{const max=Math.max(0,...snap.sections.map(s=>Number(s.sort_order)||0));snap.sections=[...snap.sections,{id:'preview-new-section',name,nav_label:name,subtitle,sort_order:max+10,visible:true}]}return snap}
 if(editCtx.kind==='sectionItem'){const payload=readForm(form,defs.sectionItem);if(editCtx.id)snap.sectionItems=snap.sectionItems.map(x=>String(x.id)===String(editCtx.id)?{...x,...payload}:x);else snap.sectionItems=[...snap.sectionItems,{id:'preview-new-entry',section_id:editCtx.sectionId,...payload}];return snap}
 if(defs[editCtx.kind]){const payload=readForm(form,defs[editCtx.kind]);if(editCtx.id)snap[editCtx.kind]=snap[editCtx.kind].map(x=>String(x.id)===String(editCtx.id)?{...x,...payload}:x);else snap[editCtx.kind]=[...snap[editCtx.kind],{id:'preview-new-item',...payload}]}return snap}
function tags(items){return arr(items).length?`<div class="lp-tags">${arr(items).map(t=>`<span class="lp-tag">${esc(t)}</span>`).join('')}</div>`:''}
function sectionItemsFor(snap,id){return arr(snap.sectionItems).filter(x=>String(x.section_id)===String(id)&&x.visible!==false).sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0))}
function timelineCard(x){const date=[x.start_label,x.end_label].filter(Boolean).join(' — ');return `<article class="lp-timeline"><div class="lp-dates">${esc(date)}</div><div class="lp-entry"><div class="lp-entry-top"><div><h4>${esc(x.company||'')}</h4><div class="lp-entry-role">${esc(x.role||'')}</div></div><div class="lp-entry-location">${esc(x.location||'')}</div></div>${x.summary?`<p>${esc(x.summary)}</p>`:''}${arr(x.achievements).length?`<ul>${arr(x.achievements).map(a=>`<li>${esc(a)}</li>`).join('')}</ul>`:''}${tags(x.technologies)}</div></article>`}
function renderPreview(){const host=document.querySelector('#live-preview-body');if(!host||typeof state==='undefined')return;const snap=draftSnapshot(),p=snap.profile||{},s=snap.settings||{};const color=/^#[0-9a-f]{6}$/i.test(val(s.accent_color))?s.accent_color:'#111827';const initials=val(p.full_name,'HY').split(/\s+/).filter(Boolean).map(x=>x[0]).slice(-2).join('').toUpperCase();const avatar=/^https?:\/\//i.test(val(p.avatar_url))?`<img src="${esc(p.avatar_url)}" alt="">`:esc(initials);const contacts=[p.email,p.phone,p.location,p.website_url,p.linkedin_url,p.github_url,p.availability].filter(Boolean).map(x=>`<span>${esc(x)}</span>`).join('');
 const highlights=arr(snap.highlights).filter(x=>x.visible!==false).sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0));
 const sections=arr(snap.sections).filter(x=>x.visible!==false).sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0));
 const projects=arr(snap.projects).filter(x=>x.visible!==false).sort((a,b)=>(Number(b.featured)||0)-(Number(a.featured)||0)||(Number(a.sort_order)||0)-(Number(b.sort_order)||0));
 const skills=arr(snap.skills).filter(x=>x.visible!==false).sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0));
 const education=arr(snap.education).filter(x=>x.visible!==false).sort((a,b)=>(Number(a.sort_order)||0)-(Number(b.sort_order)||0));
 let html=`<div class="lp-canvas lp-sync-flash" style="--lp-accent:${color}"><div class="lp-paper"><section class="lp-hero" data-preview-key="profile"><div class="lp-avatar">${avatar}</div><div><div class="lp-eyebrow">${esc(p.eyebrow||'CURRICULUM VITAE / PORTFOLIO')}</div><h2 class="lp-name">${esc(p.full_name||'HYU')}</h2><div class="lp-role" style="color:${color}">${esc(p.title||'Portfolio')}</div>${p.summary?`<p class="lp-summary">${esc(p.summary)}</p>`:''}${contacts?`<div class="lp-contact">${contacts}</div>`:''}</div></section>`;
 if(highlights.length)html+=`<section class="lp-section" data-preview-key="highlights"><div class="lp-section-head"><h3>Profile Highlights</h3><span>At a glance</span></div><div class="lp-highlights">${highlights.map(x=>`<div class="lp-highlight"><small>${esc(x.label||'')}</small><b>${esc(x.value||'')}</b><small>${esc(x.note||'')}</small></div>`).join('')}</div></section>`;
 sections.forEach(sec=>{const rows=sectionItemsFor(snap,sec.id);html+=`<section class="lp-section" data-preview-key="section-${esc(sec.id)}"><div class="lp-section-head"><h3>${esc(sec.name)}</h3><span>${esc(sec.subtitle||'Selected entries')}</span></div>${rows.length?rows.map(timelineCard).join(''):'<div class="lp-empty">No visible entries in this section.</div>'}</section>`});
 if(projects.length)html+=`<section class="lp-section" data-preview-key="projects"><div class="lp-section-head"><h3>Selected Projects</h3><span>Work & case studies</span></div><div class="lp-projects">${projects.map(x=>`<article class="lp-project"><h4>${esc(x.title||'Untitled project')}</h4><small>${esc(x.subtitle||'')}</small>${x.description?`<p>${esc(x.description)}</p>`:''}${tags(x.tags)}</article>`).join('')}</div></section>`;
 if(skills.length)html+=`<section class="lp-section" data-preview-key="skills"><div class="lp-section-head"><h3>Skills</h3><span>Core capabilities</span></div><div class="lp-skills">${skills.map(x=>{const n=Math.min(100,Math.max(0,Number(x.level)||0));return `<div class="lp-skill"><div>${esc(x.name||'')}<small>${esc(x.category||'')}</small></div><div class="lp-bar"><i style="width:${n}%"></i></div><b>${n}%</b></div>`}).join('')}</div></section>`;
 if(education.length)html+=`<section class="lp-section" data-preview-key="education"><div class="lp-section-head"><h3>Education</h3><span>Academic background</span></div>${education.map(x=>`<article class="lp-edu"><div class="lp-dates">${esc([x.start_label,x.end_label].filter(Boolean).join(' — '))}</div><div><h4>${esc(x.school||'')}</h4><p>${esc([x.degree,x.field,x.gpa&&`GPA ${x.gpa}`].filter(Boolean).join(' · '))}</p>${arr(x.highlights).length?`<ul class="lp-entry" style="font-size:8px;padding-left:14px">${arr(x.highlights).map(a=>`<li>${esc(a)}</li>`).join('')}</ul>`:''}</div></article>`).join('')}</section>`;
 html+=`<div class="lp-hidden-note">Live draft preview · hidden items are excluded · changes are not public until saved</div></div></div>`;host.innerHTML=html}
function schedulePreview(){cancelAnimationFrame(previewRAF);previewRAF=requestAnimationFrame(renderPreview)}
function syncPreview(panel=activePanel){const scroll=document.querySelector('.lp-scroll');if(!scroll)return;const key=panel==='profile'||panel==='settings'?'profile':panel;const target=scroll.querySelector(`[data-preview-key="${CSS.escape(key)}"]`);if(target)scroll.scrollTo({top:Math.max(0,target.offsetTop-18),behavior:'smooth'})}
function updateToggleLabel(){const b=document.querySelector('#live-preview-toggle');if(!b)return;if(window.innerWidth<=1180)b.textContent=document.body.classList.contains('live-preview-open')?'Close preview':'Live preview';else b.textContent=document.body.classList.contains('preview-hidden')?'Show preview':'Hide preview'}
function togglePreview(){if(window.innerWidth<=1180){document.body.classList.toggle('live-preview-open')}else{document.body.classList.toggle('preview-hidden');localStorage.setItem('hyuPreviewHidden',document.body.classList.contains('preview-hidden')?'1':'0')}updateToggleLabel();if(!document.body.classList.contains('preview-hidden'))schedulePreview()}
function install(){const layout=document.querySelector('.layout'),actions=document.querySelector('.top-actions');if(!layout||document.querySelector('.live-preview'))return;const pane=document.createElement('aside');pane.className='live-preview';pane.innerHTML=`<div class="lp-toolbar"><div class="lp-toolbar-left"><span class="lp-dot"></span><span class="lp-title">Live CV Preview</span><span class="lp-status">Draft</span></div><div class="lp-toolbar-actions"><button type="button" id="lp-reload">Reload saved</button><a href="https://hyu-portfolio-two.vercel.app" target="_blank" rel="noreferrer">Public ↗</a><button type="button" id="lp-close">×</button></div></div><div class="lp-scroll" id="live-preview-body"></div>`;layout.appendChild(pane);const toggle=document.createElement('button');toggle.type='button';toggle.id='live-preview-toggle';toggle.textContent='Hide preview';actions.insertBefore(toggle,actions.querySelector('#logout'));if(localStorage.getItem('hyuPreviewHidden')==='1'&&window.innerWidth>1180)document.body.classList.add('preview-hidden');toggle.onclick=togglePreview;document.querySelector('#lp-close').onclick=togglePreview;document.querySelector('#lp-reload').onclick=async()=>{if(typeof loadAll==='function'){await loadAll();schedulePreview()}};updateToggleLabel();schedulePreview()}
const baseRender=render;render=function(){baseRender();schedulePreview()};
const baseOpenModal=openModal;openModal=function(...args){const r=baseOpenModal(...args);schedulePreview();return r};
const baseOpenSectionModal=openSectionModal;openSectionModal=function(...args){const r=baseOpenSectionModal(...args);schedulePreview();return r};
const baseCloseModal=closeModal;closeModal=function(...args){const r=baseCloseModal(...args);schedulePreview();return r};
document.addEventListener('input',e=>{if(e.target.matches('input,textarea,select'))schedulePreview()});document.addEventListener('change',e=>{if(e.target.matches('input,textarea,select'))schedulePreview()});document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab)setTimeout(()=>syncPreview(tab.dataset.tab),40)});window.addEventListener('resize',()=>{if(window.innerWidth>1180)document.body.classList.remove('live-preview-open');updateToggleLabel()});
install();
})();
