-- HYU PREMIUM Supabase foundation
-- Run this entire file once in Supabase Dashboard -> SQL Editor.
-- It creates normalized catalogue/team tables, owner authorization, RLS, and public image buckets.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.image_credits (
  id bigint generated by default as identity primary key,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.ranks (
  id bigint generated by default as identity primary key,
  name text not null unique,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.artworks (
  id text primary key,
  name text not null,
  description text not null default '',
  category_id bigint not null references public.categories(id) on delete restrict,
  rank_id bigint not null references public.ranks(id) on delete restrict,
  credit_id bigint not null references public.image_credits(id) on delete restrict,
  image text not null,
  tags text[] not null default '{}',
  hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  image text not null,
  sort_order integer not null default 0,
  hidden boolean not null default false,
  facebook_url text not null default '',
  facebook_hidden boolean not null default false,
  tiktok_url text not null default '',
  tiktok_hidden boolean not null default false,
  instagram_url text not null default '',
  instagram_hidden boolean not null default false,
  x_url text not null default '',
  x_hidden boolean not null default false,
  linkedin_url text not null default '',
  linkedin_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists artworks_set_updated_at on public.artworks;
create trigger artworks_set_updated_at
before update on public.artworks
for each row execute function public.set_updated_at();

drop trigger if exists team_members_set_updated_at on public.team_members;
create trigger team_members_set_updated_at
before update on public.team_members
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admins a
    where a.user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.categories enable row level security;
alter table public.image_credits enable row level security;
alter table public.ranks enable row level security;
alter table public.artworks enable row level security;
alter table public.team_members enable row level security;
alter table public.admins enable row level security;

drop policy if exists "public can read categories" on public.categories;
create policy "public can read categories"
on public.categories for select
to anon, authenticated
using (true);

drop policy if exists "admins manage categories" on public.categories;
create policy "admins manage categories"
on public.categories for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "public can read credits" on public.image_credits;
create policy "public can read credits"
on public.image_credits for select
to anon, authenticated
using (true);

drop policy if exists "admins manage credits" on public.image_credits;
create policy "admins manage credits"
on public.image_credits for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "public can read ranks" on public.ranks;
create policy "public can read ranks"
on public.ranks for select
to anon, authenticated
using (true);

drop policy if exists "admins manage ranks" on public.ranks;
create policy "admins manage ranks"
on public.ranks for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "public can read visible artworks" on public.artworks;
create policy "public can read visible artworks"
on public.artworks for select
to anon
using (hidden = false);

drop policy if exists "admins can read all artworks" on public.artworks;
create policy "admins can read all artworks"
on public.artworks for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can insert artworks" on public.artworks;
create policy "admins can insert artworks"
on public.artworks for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins can update artworks" on public.artworks;
create policy "admins can update artworks"
on public.artworks for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete artworks" on public.artworks;
create policy "admins can delete artworks"
on public.artworks for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "public can read visible team members" on public.team_members;
create policy "public can read visible team members"
on public.team_members for select
to anon
using (hidden = false);

drop policy if exists "admins can read all team members" on public.team_members;
create policy "admins can read all team members"
on public.team_members for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can insert team members" on public.team_members;
create policy "admins can insert team members"
on public.team_members for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins can update team members" on public.team_members;
create policy "admins can update team members"
on public.team_members for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete team members" on public.team_members;
create policy "admins can delete team members"
on public.team_members for delete
to authenticated
using ((select public.is_admin()));

drop policy if exists "admin can read own admin record" on public.admins;
create policy "admin can read own admin record"
on public.admins for select
to authenticated
using (user_id = (select auth.uid()));

-- Least-privilege Data API grants. RLS still decides which rows are accessible.
grant select on public.categories, public.image_credits, public.ranks, public.team_members to anon;
grant select on public.artworks to anon;
grant select, insert, update, delete on public.categories, public.image_credits, public.ranks, public.artworks, public.team_members to authenticated;
grant select on public.admins to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Public bucket for artwork images. Reads are public; writes remain protected by RLS.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'artworks',
  'artworks',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "admins upload artwork files" on storage.objects;
create policy "admins upload artwork files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'artworks' and (select public.is_admin()));

drop policy if exists "admins update artwork files" on storage.objects;
create policy "admins update artwork files"
on storage.objects for update
to authenticated
using (bucket_id = 'artworks' and (select public.is_admin()))
with check (bucket_id = 'artworks' and (select public.is_admin()));

drop policy if exists "admins delete artwork files" on storage.objects;
create policy "admins delete artwork files"
on storage.objects for delete
to authenticated
using (bucket_id = 'artworks' and (select public.is_admin()));

-- Public bucket for 1:1 About Us team portraits.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'team',
  'team',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "admins upload team files" on storage.objects;
create policy "admins upload team files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'team' and (select public.is_admin()));

drop policy if exists "admins update team files" on storage.objects;
create policy "admins update team files"
on storage.objects for update
to authenticated
using (bucket_id = 'team' and (select public.is_admin()))
with check (bucket_id = 'team' and (select public.is_admin()));

drop policy if exists "admins delete team files" on storage.objects;
create policy "admins delete team files"
on storage.objects for delete
to authenticated
using (bucket_id = 'team' and (select public.is_admin()));

-- After creating your first Supabase Auth user, make that user the owner by running:
-- insert into public.admins (user_id) values ('YOUR_AUTH_USER_UUID') on conflict do nothing;
