-- HYU PREMIUM SEO Manager backend
-- Applied to production as migration: seo_manager_backend

create table if not exists public.seo_global_settings (
  id boolean primary key default true check (id),
  site_name text not null default 'HYU PREMIUM',
  site_url text not null default 'https://hyupremium.vercel.app',
  default_title text not null default 'HYU PREMIUM — Gaming Splash Art Archive',
  title_template text not null default '%s | HYU PREMIUM',
  default_description text not null default 'A curated searchable archive of gaming splash art organized by character/category, skin rank and image credit.',
  default_og_image text not null default '', default_locale text not null default 'vi_VN',
  google_site_verification text not null default 'KMBRePIo30hKHau-mQc3tM_H0bELdtJRxXfo8I1PDGE',
  llms_summary text not null default 'HYU PREMIUM is an owner-curated gaming splash-art archive with permanent artwork pages organized by character, skin rank and image credit.',
  llms_key_pages jsonb not null default '["/character/","/artworks/","/about/","/news/","/blog/"]'::jsonb,
  ai_crawlers jsonb not null default '{"GPTBot":true,"ChatGPT-User":true,"PerplexityBot":true,"ClaudeBot":true,"anthropic-ai":true,"Google-Extended":true,"bingbot":true}'::jsonb,
  updated_at timestamptz not null default now(), updated_by uuid
);
insert into public.seo_global_settings(id) values(true) on conflict(id) do nothing;

create table if not exists public.seo_page_overrides (
  id uuid primary key default gen_random_uuid(), path text not null unique check(path like '/%'), page_type text not null default 'page', entity_id text,
  target_keyword text not null default '', keywords text[] not null default '{}'::text[], title text not null default '', meta_description text not null default '', canonical_url text not null default '', h1_suggestion text not null default '', image_alt text not null default '', og_title text not null default '', og_description text not null default '', og_image text not null default '',
  robots_index boolean not null default true, robots_follow boolean not null default true, include_in_sitemap boolean not null default true,
  schema_json jsonb not null default '{}'::jsonb, ai_summary text not null default '', ai_key_facts jsonb not null default '[]'::jsonb, ai_faq jsonb not null default '[]'::jsonb,
  enabled boolean not null default true, updated_at timestamptz not null default now(), updated_by uuid
);
create index if not exists seo_page_overrides_type_idx on public.seo_page_overrides(page_type);
create index if not exists seo_page_overrides_entity_idx on public.seo_page_overrides(entity_id);

create table if not exists public.seo_query_targets (
  id bigint generated by default as identity primary key, query text not null, intent text not null default '', platform text not null default 'all', priority smallint not null default 3 check(priority between 1 and 5), active boolean not null default true, notes text not null default '', cited boolean, cited_url text not null default '', competitors jsonb not null default '[]'::jsonb, last_checked_at timestamptz, updated_at timestamptz not null default now(), updated_by uuid
);
create unique index if not exists seo_query_targets_query_platform_idx on public.seo_query_targets(lower(query),lower(platform));

create table if not exists public.seo_change_log (
  id bigint generated by default as identity primary key, source_table text not null, record_key text not null, action text not null, before_data jsonb, after_data jsonb, user_id uuid, created_at timestamptz not null default now()
);
create index if not exists seo_change_log_created_idx on public.seo_change_log(created_at desc);

create or replace function public.seo_touch_updated_at() returns trigger language plpgsql as $$ begin new.updated_at=now();new.updated_by=auth.uid();return new;end; $$;
create or replace function public.seo_audit_change() returns trigger language plpgsql security definer set search_path=public as $$
declare key_value text;begin key_value=coalesce((case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end)->>'path',(case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end)->>'id','global');insert into public.seo_change_log(source_table,record_key,action,before_data,after_data,user_id) values(tg_table_name,key_value,tg_op,case when tg_op in('UPDATE','DELETE') then to_jsonb(old) end,case when tg_op in('INSERT','UPDATE') then to_jsonb(new) end,auth.uid());return case when tg_op='DELETE' then old else new end;end; $$;

drop trigger if exists seo_global_touch on public.seo_global_settings;create trigger seo_global_touch before update on public.seo_global_settings for each row execute function public.seo_touch_updated_at();
drop trigger if exists seo_page_touch on public.seo_page_overrides;create trigger seo_page_touch before update on public.seo_page_overrides for each row execute function public.seo_touch_updated_at();
drop trigger if exists seo_target_touch on public.seo_query_targets;create trigger seo_target_touch before update on public.seo_query_targets for each row execute function public.seo_touch_updated_at();
drop trigger if exists seo_global_audit on public.seo_global_settings;create trigger seo_global_audit after insert or update or delete on public.seo_global_settings for each row execute function public.seo_audit_change();
drop trigger if exists seo_page_audit on public.seo_page_overrides;create trigger seo_page_audit after insert or update or delete on public.seo_page_overrides for each row execute function public.seo_audit_change();
drop trigger if exists seo_target_audit on public.seo_query_targets;create trigger seo_target_audit after insert or update or delete on public.seo_query_targets for each row execute function public.seo_audit_change();

alter table public.seo_global_settings enable row level security;alter table public.seo_page_overrides enable row level security;alter table public.seo_query_targets enable row level security;alter table public.seo_change_log enable row level security;
create policy "public can read seo global settings" on public.seo_global_settings for select to anon,authenticated using(true);
create policy "admins manage seo global settings" on public.seo_global_settings for all to authenticated using((select is_admin())) with check((select is_admin()));
create policy "public can read enabled seo page overrides" on public.seo_page_overrides for select to anon,authenticated using(enabled=true);
create policy "admins can read all seo page overrides" on public.seo_page_overrides for select to authenticated using((select is_admin()));
create policy "admins manage seo page overrides" on public.seo_page_overrides for all to authenticated using((select is_admin())) with check((select is_admin()));
create policy "admins manage seo query targets" on public.seo_query_targets for all to authenticated using((select is_admin())) with check((select is_admin()));
create policy "admins read seo change log" on public.seo_change_log for select to authenticated using((select is_admin()));
grant select on public.seo_global_settings to anon,authenticated;grant select on public.seo_page_overrides to anon,authenticated;grant insert,update,delete on public.seo_global_settings to authenticated;grant insert,update,delete on public.seo_page_overrides to authenticated;grant select,insert,update,delete on public.seo_query_targets to authenticated;grant select on public.seo_change_log to authenticated;grant usage,select on all sequences in schema public to authenticated;
