-- HYU PREMIUM / About Us / Our Team
-- Existing-project migration. Run this file once in Supabase Dashboard -> SQL Editor.
-- It creates the team_members table, RLS policies and the public team image bucket.

create table if not exists public.team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  image text not null,
  sort_order integer not null default 0,
  hidden boolean not null default false,
  facebook_url text not null default '',
  facebook_hidden boolean not null default false,
  tiktok_url text not null default '',
  tiktok_hidden boolean not null default false,
  instagram_url text not null default '',
  instagram_hidden boolean not null default false,
  x_url text not null default '',
  x_hidden boolean not null default false,
  linkedin_url text not null default '',
  linkedin_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Reuse the foundation trigger function when it already exists.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists team_members_set_updated_at on public.team_members;
create trigger team_members_set_updated_at
before update on public.team_members
for each row execute function public.set_updated_at();

alter table public.team_members enable row level security;

drop policy if exists "public can read visible team members" on public.team_members;
create policy "public can read visible team members"
on public.team_members for select
to anon
using (hidden = false);

drop policy if exists "admins can read all team members" on public.team_members;
create policy "admins can read all team members"
on public.team_members for select
to authenticated
using ((select public.is_admin()));

drop policy if exists "admins can insert team members" on public.team_members;
create policy "admins can insert team members"
on public.team_members for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists "admins can update team members" on public.team_members;
create policy "admins can update team members"
on public.team_members for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "admins can delete team members" on public.team_members;
create policy "admins can delete team members"
on public.team_members for delete
to authenticated
using ((select public.is_admin()));

grant select on public.team_members to anon;
grant select, insert, update, delete on public.team_members to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'team',
  'team',
  true,
  10485760,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "admins upload team files" on storage.objects;
create policy "admins upload team files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'team' and (select public.is_admin()));

drop policy if exists "admins update team files" on storage.objects;
create policy "admins update team files"
on storage.objects for update
to authenticated
using (bucket_id = 'team' and (select public.is_admin()))
with check (bucket_id = 'team' and (select public.is_admin()));

drop policy if exists "admins delete team files" on storage.objects;
create policy "admins delete team files"
on storage.objects for delete
to authenticated
using (bucket_id = 'team' and (select public.is_admin()));
