import type { Metadata } from 'next';
import CatalogueFreshnessGuard from '@/components/CatalogueFreshnessGuard';
import GalleryClient from '@/components/GalleryClient';
import { SiteFooter, SiteHeader } from '@/components/SiteChrome';
import type { Artwork } from '@/lib/catalogue';
import { artworkPath, artworkPreview, artworkSocialImage, factualDescription, findArtwork, getCatalogue, siteUrl, slug } from '@/lib/catalogue';
import { applySeoOverride, getSeoGlobalSettings, getSeoOverride } from '@/lib/seo';

export const revalidate = 300;
type PageProps = { params: Promise<{ segments?: string[] }> };

function localizedAlternates(url:string){return {canonical:url,languages:{vi:url,'x-default':url}}}
function seoForArtwork(item:Artwork){
  const vietnamese=item.isVietnameseSkin;
  const title=vietnamese?`${item.category} ${item.name} – Skin Việt Nam Liên Quân`:`${item.category} ${item.name} – Fanart Liên Quân`;
  const description=vietnamese?`Skin Việt Nam tự làm ${item.category} ${item.name} cho Liên Quân Mobile. Xem fanart splash art, hạng ${item.rank}, credit ${item.credit} và các tác phẩm liên quan.`:factualDescription(item);
  const alt=vietnamese?`Splash art skin Việt Nam tự làm ${item.name} của ${item.category} trong Liên Quân Mobile`:`${item.name} — ${item.category}, splash art game, hạng skin ${item.rank}`;
  const keywords=[`${item.category} ${item.name}`,`skin ${item.category} ${item.name}`,`fanart ${item.category}`,`skin fanmade ${item.category}`,'fanart Liên Quân Mobile','skin fanmade Liên Quân','skin tự làm Liên Quân','splash art Liên Quân','Arena of Valor fanart',...(vietnamese?['skin Việt Nam Liên Quân','skin Việt Nam tự làm','fanmade skin Việt Nam','fanart Việt Nam Liên Quân']:[]),...item.tags].filter(Boolean);
  const aliases=[`${item.category} ${item.name}`,`${item.name} ${item.category}`,`${item.category} ${slug(item.name).replace(/-/g,' ')}`,`${item.category}: ${item.name}`];
  const answer=vietnamese?`${item.name} là concept skin Việt Nam tự làm dành cho ${item.category} trong Liên Quân Mobile (Arena of Valor), được lưu trữ trong HYU PREMIUM như một fanart/splash art fanmade. Tác phẩm có hạng skin ${item.rank} và credit ảnh ${item.credit}. Trang này cung cấp ảnh gốc cùng các fanart ${item.category} liên quan trong bộ sưu tập.`:factualDescription(item);
  return {title,description,alt,keywords,aliases,answer};
}
function routePath(segments:string[],category:string|null,artwork:Artwork|null){if(artwork)return artworkPath(artwork);if(category)return `/character/${segments[0]}/`;return '/character/'}

export async function generateMetadata({params}:PageProps):Promise<Metadata>{
  const {segments=[]}=await params;const catalogue=await getCatalogue();const {category,artwork}=findArtwork(catalogue.items,segments[0],segments[1]);const path=routePath(segments,category,artwork);const [global,override]=await Promise.all([getSeoGlobalSettings(),getSeoOverride(path)]);let base:Metadata;
  if(artwork){const url=`${siteUrl}${artworkPath(artwork)}`,seo=seoForArtwork(artwork),social=artworkSocialImage(artwork);base={title:{absolute:seo.title},description:seo.description,keywords:seo.keywords,alternates:localizedAlternates(url),robots:{index:true,follow:true,googleBot:{index:true,follow:true,'max-image-preview':'large','max-snippet':-1,'max-video-preview':-1}},openGraph:{title:seo.title,description:seo.description,url,type:'article',locale:'vi_VN',images:[{url:social,alt:seo.alt}]},twitter:{card:'summary_large_image',title:seo.title,description:seo.description,images:[{url:social,alt:seo.alt}]}}}
  else if(category){const url=`${siteUrl}/character/${segments[0]}/`,title=`${category} — Thư viện Splash Art`,description=`Khám phá các splash art ${category} trong HYU PREMIUM, có thể lọc theo hạng skin và credit ảnh.`;base={title,description,alternates:localizedAlternates(url),openGraph:{title,description,url,type:'website',locale:'vi_VN'}}}
  else{const rootUrl=`${siteUrl}/character/`;base={title:{absolute:'HYU PREMIUM — Thư viện Splash Art Game'},description:'Thư viện splash art game được tuyển chọn, có thể tìm kiếm và lọc theo nhân vật, danh mục, hạng skin và credit ảnh.',alternates:localizedAlternates(rootUrl),openGraph:{url:rootUrl,type:'website',locale:'vi_VN'}}}
  return applySeoOverride(base,override,global);
}

export default async function CharacterGalleryPage({params}:PageProps){
  const {segments=[]}=await params;const catalogue=await getCatalogue();const route=findArtwork(catalogue.items,segments[0],segments[1]);const artwork=route.artwork;const path=routePath(segments,route.category,artwork);const override=await getSeoOverride(path);const routeItems=route.category?catalogue.items.filter(item=>item.category===route.category):catalogue.items;
  const itemList={'@context':'https://schema.org','@type':'CollectionPage',name:route.category?`${route.category} — Thư viện Splash Art`:'HYU PREMIUM — Thư viện Splash Art Game',url:`${siteUrl}${route.category?`/character/${segments[0]}/`:'/character/'}`,mainEntity:{'@type':'ItemList',numberOfItems:routeItems.length,itemListElement:routeItems.map((item,index)=>({'@type':'ListItem',position:index+1,url:`${siteUrl}${artworkPath(item)}`,name:item.name,image:artworkPreview(item,960)}))}};
  const seo=artwork?seoForArtwork(artwork):null;const pageUrl=artwork?`${siteUrl}${artworkPath(artwork)}`:'';const crawlerImage=artwork?.variants?.['1600'];
  const artworkJsonLd=artwork&&seo?{'@context':'https://schema.org','@graph':[
    {'@type':'WebPage','@id':`${pageUrl}#webpage`,url:pageUrl,name:override?.title||seo.title,description:override?.meta_description||seo.description,isPartOf:{'@type':'WebSite','@id':`${siteUrl}/#website`,url:`${siteUrl}/`,name:'HYU PREMIUM'},primaryImageOfPage:{'@id':`${pageUrl}#image`},breadcrumb:{'@id':`${pageUrl}#breadcrumb`},inLanguage:'vi-VN',mainEntity:{'@id':`${pageUrl}#artwork`},about:{'@type':'VideoGame',name:'Liên Quân Mobile',alternateName:'Arena of Valor'},keywords:(override?.keywords?.length?override.keywords:seo.keywords).join(', '),dateModified:artwork.updatedAt},
    {'@type':'ImageObject','@id':`${pageUrl}#image`,contentUrl:crawlerImage?.url||artworkPreview(artwork,1600),thumbnailUrl:artworkPreview(artwork,960),name:`${artwork.name} — ${artwork.category}`,caption:artwork.isVietnameseSkin?`${artwork.category} ${artwork.name} – Skin Việt Nam Tự Làm Liên Quân`:`${artwork.category} ${artwork.name} splash art`,creditText:artwork.credit,representativeOfPage:true,description:override?.image_alt||seo.alt,about:{'@type':'VideoGame',name:'Liên Quân Mobile',alternateName:'Arena of Valor'},inLanguage:'vi-VN',width:crawlerImage?.width||undefined,height:crawlerImage?.height||undefined,contentSize:crawlerImage?.bytes?`${crawlerImage.bytes} bytes`:undefined,encodingFormat:crawlerImage?.mimeType||undefined},
    {'@type':['VisualArtwork','CreativeWork'],'@id':`${pageUrl}#artwork`,url:pageUrl,name:artwork.name,description:override?.ai_summary||seo.answer,image:{'@id':`${pageUrl}#image`},genre:artwork.isVietnameseSkin?['Fan art','Fanmade game skin','Skin Việt Nam tự làm','Splash art']:['Fan art','Fanmade game skin','Splash art'],keywords:(override?.keywords?.length?override.keywords:seo.keywords).join(', '),headline:override?.title||seo.title,alternateName:seo.aliases,artform:'Fan art / concept skin game fanmade',artMedium:'Minh họa kỹ thuật số',about:{'@type':'VideoGame',name:'Liên Quân Mobile',alternateName:'Arena of Valor'},inLanguage:'vi-VN',dateModified:artwork.updatedAt},
    {'@type':'BreadcrumbList','@id':`${pageUrl}#breadcrumb`,itemListElement:[{'@type':'ListItem',position:1,name:'HYU PREMIUM',item:`${siteUrl}/`},{'@type':'ListItem',position:2,name:'Thư viện',item:`${siteUrl}/character/`},{'@type':'ListItem',position:3,name:artwork.category,item:`${siteUrl}/character/${slug(artwork.category)}/`},{'@type':'ListItem',position:4,name:artwork.name,item:pageUrl}]}
  ]}:null;
  const customSchema=override?.schema_json&&Object.keys(override.schema_json).length?override.schema_json:null;
  return <><SiteHeader/><CatalogueFreshnessGuard revision={catalogue.revision}/><section className="hero" id="top"><div className="hero-kicker"><i></i> Bộ sưu tập game art được tuyển chọn</div><h1>Nghệ thuật<br/>của <em>trò chơi.</em></h1><div className="hero-foot"><p>Thư viện luôn được cập nhật, sắp xếp theo nhân vật hoặc danh mục và hệ thống hạng skin riêng.</p><span>Cuộn xuống để khám phá ↓</span></div></section><GalleryClient catalogue={catalogue} initialCategory={route.category} initialArtworkId={artwork?.id||null}/><section className="manifesto"><p className="eyebrow">HYU PREMIUM / THƯ VIỆN</p><h2>Mỗi khung hình là<br/>một thế giới <em>đang chờ.</em></h2><div className="manifesto-copy"><p>Một thư viện splash art được quản lý thủ công, giữ bố cục 16:9 nhất quán và sắp xếp rõ ràng theo danh mục, hạng skin.</p><p>Metadata được quản lý bằng GitHub, ảnh được phân phối qua Cloudflare R2, còn các trang SEO được render phía máy chủ để dễ tìm kiếm và chia sẻ.</p></div></section><SiteFooter/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(itemList).replace(/</g,'\\u003c')}}/>{artworkJsonLd?<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(artworkJsonLd).replace(/</g,'\\u003c')}}/>:null}{customSchema?<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(customSchema).replace(/</g,'\\u003c')}}/>:null}</>;
}
